---

name: Release
on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null
permissions:
  contents: write

jobs:

  release:
    name: Release from push
    runs-on: ubuntu-latest
    steps:

      - name: Pause until all workflows are completed
        uses: willgarcia/workflow-wait-action@main
        with:
          interval: 2
          initial_delay: 40

      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse Changelog
        id: changelog
        uses: coditory/changelog-parser@v1

      - name: Changelog description output
        run: echo "${{ steps.changelog.outputs.description }}"

      - name: Create a release
        id: release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: v${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.description }}
          tag: v${{ steps.changelog.outputs.version }}
          generateReleaseNotes: false
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ env.BINARY_NAME }}