---
name: Release CI
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  release:
    name: Release from push
    runs-on: ubuntu-latest
    steps:
      - name: Pause until all workflows are completed
        uses: willgarcia/workflow-wait-action@main
        with:
          interval: 2
          initial_delay: 40

      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse Changelog
        id: changelog
        uses: coditory/changelog-parser@v1

      - name: Paste version to source file
        run: sed -i "s/^\s\*\s${LINE_PATTERN}.*$/ * ${LINE_PATTERN} ${VERSION}/" "$FILENAME"
        env:
          LINE_PATTERN: Jenkins Universal Wrapper Pipeline
          VERSION: v${{ steps.changelog.outputs.version }}
          FILENAME: jenkins-universal-wrapper-pipeline.groovy

      - name: Push changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated version increment v${{ steps.changelog.outputs.version }}
          file_pattern: jenkins-universal-wrapper-pipeline.groovy

      - name: Create a release
        id: release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: v${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.description }}
          tag: v${{ steps.changelog.outputs.version }}
          generateReleaseNotes: false
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ env.BINARY_NAME }}
